jenkins:

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "letmein"

jobs:
  - script: >

      folder('test-folder') {
        description('Test folder')
      }

      pipelineJob('test-folder/test-job') {
        definition {
          cpsScm {
            scm {
              git('https://github.com/AlphaHydrae/jenkins-experiments.git')
            }
          }
        }
      }

security:
  remotingCLI:
    enabled: false

unclassified:

  gitscm:
    globalConfigName: Jenkins
    globalConfigEmail: jenkins@domain.local

  location:
    adminAddress: jenkins@domain.local
    url: http://localhost:7000/
