jenkins:

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: admin
            description: Jenkins administrators
            permissions:
              - Overall/Administer
            assignments:
              - admin

  crumbIssuer: standard

  nodes:
    - permanent:
        labelString: Agent
        mode: NORMAL
        name: agent
        nodeProperties:
          - envVars:
              env:
                - key: GIT_AUTHOR_NAME
                  value: Jenkins
                - key: GIT_AUTHOR_EMAIL
                  value: jenkins@domain.local
                - key: GIT_COMMITTER_NAME
                  value: Jenkins
                - key: GIT_COMMITTER_EMAIL
                  value: jenkins@domain.local
        numExecutors: 2
        remoteFS: /home/jenkins/data
        launcher:
          command:
            command: ssh -i /etc/jenkins/id_rsa jenkins@192.168.50.31 /usr/bin/sudo /home/jenkins/bin/run-jenkins-agent.sh

  remotingSecurity:
    enabled: true

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: letmein

jobs:
  - script: >

      folder('test-folder') {
        description('Test folder')
      }

      pipelineJob('test-folder/test-job') {
        definition {
          cpsScm {
            scm {
              git('https://github.com/AlphaHydrae/jenkins-experiments.git')
            }
          }
        }
      }

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  remotingCLI:
    enabled: false

unclassified:

  gitscm:
    globalConfigName: Jenkins
    globalConfigEmail: jenkins@domain.local

  location:
    adminAddress: jenkins@domain.local
    url: http://localhost:7000/
