version: '3.7'

services:

  master:
    image: jenkins-experiments/master
    build:
      context: .
    environment:
      CASC_JENKINS_CONFIG: /etc/jenkins/casc_configs
    ports:
      - "7000:8080"
    restart: "always"
    volumes:
      - "./casc_configs:/etc/jenkins/casc_configs"
      - "master_data:/var/jenkins_home"

volumes:
  master_data:
